### ISSUE TITLE
[BUG] can't open or create any clans

### ISSUE THREAD

**Issue by rustykitty** [ClanGenOfficial/clangen#5656]
### Pre-requisites

- [x] I have searched the existing issues
- [x] This issue was encountered (or replicated) on a non-edited Clan
- [x] I confirm that I am NOT playing on a modded version of the game (e.g. LifeGen)

### Description

When opening some existing clans, I'm getting an error on null white patches. An error log doesn't pop up, but the `continue` button is greyed out.
When creating new clans, I got a crash on Cat not having an `assign_backstory` function.

### Grade

Game-breaking - makes it impossible to play the game

### Gamemode

Classic Mode

### Steps to reproduce the behavior

1. Load or create clan
2. Check error log

### Commit # or Game Version Number

https://github.com/ClanGenOfficial/clangen/commit/0b4a75772f89dcd637b1fc00114b0f4a566c8e41

### Error log

White patches null error when loading existing clan:
```py
root - ERROR - main.py / load_data / 83 - File failed to load
Traceback (most recent call last):
  File "/home/rusty/coding/clangen/main.py", line 78, in load_data
    load_cats()
  File "/home/rusty/coding/clangen/scripts/game_structure/load_cat.py", line 45, in load_cats
    json_load()
  File "/home/rusty/coding/clangen/scripts/game_structure/load_cat.py", line 78, in json_load
    cat = LoadCatFactory.create_cat(**cat_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rusty/coding/clangen/scripts/cat/factories/load_cat_factory.py", line 44, in create_cat
    pelt = cls._build_pelt(kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rusty/coding/clangen/scripts/cat/factories/load_cat_factory.py", line 220, in _build_pelt
    if kwargs.get("tint").lower() == "none":
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```
Backstory error when creating new clan:
```
root - CRITICAL - init.py / log_crash / 78 - Uncaught exception (ClanGen 0b4a75772f89dcd637b1fc00114b0f4a566c8e41)
Traceback (most recent call last):
  File "/home/rusty/coding/clangen/main.py", line 209, in <module>
    ).handle_event(event)
      ^^^^^^^^^^^^^^^^^^^
  File "/home/rusty/coding/clangen/scripts/screens/make_clan_screens/ChooseModeScreen.py", line 149, in handle_event
    self.save_clan()
  File "/home/rusty/coding/clangen/scripts/screens/make_clan_screens/MakeClanScreenBase.py", line 258, in save_clan
    game.clan.create_clan()
  File "/home/rusty/coding/clangen/scripts/clan.py", line 318, in create_clan
    c.assign_backstory()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Cat' object has no attribute 'assign_backstory'
```

### Additional context

Likely caused by #5639 (`CatFactory`).

### Screenshots

<img width="800" height="732" alt="Image" src="https://github.com/user-attachments/assets/0ef67067-a12f-4466-b201-340dc8d09f39" />

No error popup.
